another readme rewrite
idom-team/idom pull request #739
Opened 2022-04-16 21:19 UTC by rmorshea

Yet another take on the README. Not sure I like it yet, but I think it's more inline with how I imagine it looking in the end.

2022-04-16 21:20 UTC, rmorshea commented on src/idom/_option.py
> +            stacklevel=3,
Not related, just something I and wanted to improve caught.

2022-04-17 00:06 UTC, Archmonger requested changes
I personally dislike this one. It really doesn't give a top-level highlight of the main reasons why anyone would ever want to use IDOM.

The main thing about the readme is trying to "sell" IDOM to people who haven't read the docs yet. We need to highlight all our selling points as concisely as possible. 90% of people will never read the docs.

In my previous PR, I listed the main things that I consider selling points for new developers.

Also, we definitely want to avoid tech jargon in any readme we create. Words such as "declarative" shouldn't make it in.

2022-04-17 01:13 UTC, rmorshea commented
Good point.

2022-04-17 03:08 UTC, rmorshea commented
I think the README more directly gets at the features IDOM provides, but it's also more scattershot now. Maybe there's too much that we're trying to fit into it?

Rather than throwing all the features at the reader at once we focus on something like 3:

- Write apps without JS
- Integration with web frameworks like FastAPI, Django, etc
- React-style components in Python

@acivitillo or @liberty-rising do you have some thoughts on what the reader our should come away with from the README?

2022-04-17 03:08 UTC, rmorshea commented
I'm gonna close this and open a discussion.

2022-04-17 03:08 UTC, closed without merging