add mypy plugin
idom-team/idom pull request #825
Opened 2022-10-20 06:33 UTC by rmorshea

Partially addresses: https://github.com/idom-team/idom/issues/794
closes: #616
closes: #615 

This works around the problem that the `@component` decorator hides the signature of the underlying function. Also check for improperly passing children via `*args`

All you need to do to run this is configure MyPy with:

```
[mypy]
plugins = idom.mypy
```

## Checklist

Please update this checklist as you complete each item:

- [ ] Tests have been included for all bug fixes or added functionality.
- [ ] The `changelog.rst` has been updated with any significant changes.
- [ ] GitHub Issues which may be closed by this Pull Request have been linked.

2022-10-20 06:38 UTC, Archmonger commented on src/idom/mypy.py
> +        if fullname == "idom.core.component.component":
Are we allowed to do an `from idom import component` and then have this check be `fullname == f"{component.__module}.{component.__name__}"`? 

Would improve refactorability.

2022-10-20 06:45 UTC, Archmonger requested changes
This is not the ideal solution, as it prioritizes MyPy over any other type checkers (ex `pylance`).

We will need to create an issue to revisit this when Python 3.11 becomes mainstream with better type hinting support

2022-10-20 06:45 UTC, Archmonger commented on setup.cfg
> +plugins = idom.mypy
We need to document this somehow.

Undocumented features essentially do not exist.

2022-10-20 06:58 UTC, Archmonger commented on src/idom/mypy.py
> +        if fullname == "idom.core.component.component":
Yes, however, if we decide to change the path `ido.core.component.component` in the future, this plugin will break silently.

I would recommend using python imports to generate that path, that way refactoring libraries such as [`rope`](https://github.com/python-rope/rope) can automatically update these paths. Or at the very least, this plugin would create a visible exception to demonstrate that things are broken.

2022-10-20 07:02 UTC, rmorshea commented
> This is not the ideal solution, as it prioritizes MyPy over any other type checkers (ex pylance).

I realize that, but there simply isn't any way to annotate what `@component` does with the typing tools Python provides right now. PyRight, the type checker in PyLance, also has [no support for plugins](https://github.com/microsoft/pyright/issues/607) and it doesn't seem like there will be any time soon. 

Other very large projects have already opted to write MyPy plugins. For example, [Numpy](https://numpy.org/devdocs/reference/typing.html#mypy-plugin) and [Pydantic](https://pydantic-docs.helpmanual.io/mypy_plugin/). So I don't think it's too crazy for us to do the same.

> We will need to create an issue to revisit this when Python 3.11 becomes mainstream

Typically, even if typing tools are included in newer versions of Python, they can still be used through [`typing_extensions`](https://github.com/python/typing_extensions). This is how we use newer features like `Protocol` and `ParamSpec` even though those were not released in Python 3.7 (the oldest version of Python we support). But again, there are no typing PEPs that have been accepted thus far that would allow us to appropriately annotate what `@component` does, especially after we make [this change](https://github.com/idom-team/idom/issues/755).

> Also, test seem broken for potentially unrelated reasons.

This is addressed in https://github.com/idom-team/idom/pull/823

2022-12-02 08:16 UTC, Archmonger commented on temp.py
> +temp(*[1, 2])
We might want to put `temp.py` into the gitignore if you frequently use it for testing

2022-12-07 01:21 UTC, Archmonger commented
I have been experimenting with the new [OpenAI Public Beta](https://chat.openai.com/chat) to see if it can auto complete this PR.

## Input
Create a MyPy plugin that only warns if the unpacking operator (`*` or `**`) is used within an `idom.html.*` function call of within a decorated function. This must only apply to functions decorated with `@component`. The `@component` decorator path must resolve to `idom.core.component.component`

## Output

Here is a possible implementation of a MyPy plugin that satisfies the requirements you specified:

```python
import ast
from typing import Any, Dict, List, Tuple

from mypy.plugin import FunctionContext, MethodContext, Plugin
from mypy.types import CallableType

def is_idom_html_function(func_name: str) -> bool:
    return func_name.startswith('idom.html.')

def is_component_decorated(decorators: List[ast.AST]) -> bool:
    if not decorators:
        return False
    return any(
        isinstance(decorator, ast.Name) and decorator.id == 'component'
        for decorator in decorators
    )

class IdomMypyPlugin(Plugin):
    def get_function_hook(self, fullname: str) -> Optional[Callable[[FunctionContext], Type]]:
        if fullname == 'idom.core.component.component':
            return function_hook

    def function_hook(ctx: FunctionContext) -> Type:
        sig = ctx.default_return_type
        if not isinstance(sig, CallableType):
            return sig
        if not is_component_decorated(ctx.func.decorators):
            return sig
        if not sig.is_var_arg:
            return sig
        ctx.api.warn_unused('W001', ctx.context, ctx.func, 'Unpacking operator used in decorated function')
        return sig
```

This plugin defines a single function hook that is called for any function with the full name idom.core.component.component. This function checks if the function being called is decorated with @component, and if it is, it checks if the function has a variable argument (*args or **kwargs) and if it does, it emits a warning using the MyPy API.

Note that this implementation is just an example and may not be complete or correct in all cases. MyPy plugins can be complex to write, so it's important to thoroughly test and debug them before using them in production.

2023-02-21 08:28 UTC, rmorshea commented
Gonna close this. We can return to this for reference when the time comes.

2023-02-21 08:28 UTC, closed without merging